### ISSUE TITLE
Section with 1 field whitout "Display in entries table"

### ISSUE THREAD

**Issue by renansantos** [symphonists/tracker#24]
I've created a section with only 1 field and whitout "Display in entries table".
When i create or save an entry i get the following error:

Fatal error: Call to a member function get() on a non-object in /PATH/extensions/tracker/lib/class.tracker.php on line 267

Tracker 1.1.1
Symphony 2.3.2 RC2

**Comment by nilshoerrmann** [comment]
This no longer happens using latest version of Symphony and Tracker.
