### ISSUE TITLE
Trying to delete an Authors throws error

### ISSUE THREAD

**Issue by animaux** [symphonists/tracker#25]
Same behavior with Tracker `1.1.1`, `1.2` and `1.2.1` on `Symphony 2.3.6`:

    16. July 2014 14:04 > Warning: GenericErrorHandler 2: Invalid argument supplied for foreach() on line 466 of file /www/htdocs/…/2014/extensions/tracker/extension.driver.php
    16. July 2014 14:04 > UNKNOWN: ErrorException 0 - Invalid argument supplied for foreach() on line 466 of /www/htdocs/…/2014/extensions/tracker/extension.driver.php

**Comment by jurajkapsz** [comment]
Still an issue in latest version. @nitriques ?

**Comment by cmnstmntmn** [comment]
i confirm this with
latest version of tracker and symphony

`An error occurred in /Users/ctin/repos/w/extensions/tracker/extension.driver.php around line 469
464 } else {
465 $ids = $context['author_ids'];
466 }
467
468 // Log it.
469 foreach ($ids as $id) {
470 Tracker::log(
471 'authors',
472 $id,
473 $action,`

**Comment by jurajkapsz** [comment]
Also mentioned in https://github.com/symphonists/tracker/issues/5

**Comment by nitriques** [comment]
can you 

```php
var_dump($context);die;
```

On line 467 please ?

**Comment by animaux** [comment]
Will do, but I am currently on vacation. Will report back early July, cheers!

**Comment by nitriques** [comment]
No stress, have fun!

**Comment by animaux** [comment]
Ah, error fixed in my absence. Brilliant, thanks!
