### ISSUE TITLE
Access denied - CSRF

### ISSUE THREAD

**Issue by jurajkapsz** [symphonists/tracker#26]
In Symphony 2.6, when having enabled `enable_xsrf` (is by default), clearing of Tracker's log throws an

    Access Denied. Request was rejected for having an invalid cross-site request forgery token. Please go back and try again.

error.

Tracker version 1.2.1

**Comment by nitriques** [comment]
The problem is that the content page is not well implemented

https://github.com/symphonists/tracker/blob/master/content/content.index.php#L20-L29

Those line should use the $this->Form attribute instead of creating their own. This will make sure the xsrf token gets generated.

see https://github.com/symphonycms/symphony-2/blob/22bc0f5683982dd3b0c638e07081f8da813a2727/symphony/lib/core/class.administration.php#L493-L495

**Comment by jurajkapsz** [comment]
Thanks for the info!

Ok, I don't understand fully how it all works, but I've tried to recreate the form for the [subheading](https://github.com/symphonists/tracker/blob/master/content/content.index.php#L26) using the `Widget::Form`, because I haven't found an example on that, there are used like always only anchors looking like buttons in subheading, but anyway, the Form Widget also does not have a token. Does this makes the Widget unusable under xsfr enabled?

Or how can I create a proper form in the subheading?

![image](https://cloud.githubusercontent.com/assets/2209893/8014674/de68954a-0bd2-11e5-8a26-ce3d6dc32458.png)

I know this is an offtopic question, but I think it would lost this straight context when asked elsewhere.

**Comment by nitriques** [comment]
> he Form Widget also does not have a token. Does this makes the Widget unusable under xsfr enabled?

Those are the two lines we are missing...

https://github.com/symphonycms/symphony-2/blob/2.6.x/symphony/template/usererror.missing_extension.php#L138-L140

Just copy paste them before this line https://github.com/symphonists/tracker/blob/master/content/content.index.php#L177

And please.. send a PR ! :)

**Comment by jurajkapsz** [comment]
I see, thanks!

I have a working PR locally (made a bit differently but using your lines), want to finish up also a localization. Will push these.

Also, does it makes sense to add this token generator to the Widget Form as an automated process?

**Comment by jurajkapsz** [comment]
Huh, another question, will this XSFR support break compatibility with Symphony 2.4? Because I could also push a version update probably to `1.3`.

And with this I am thinking about the localization I want to create, that it would fit also to Symphony 2.4 version. But if that XSFR support breaks compatibility, how to do it then. Maybe to release two new versions - one for Sym 2.4 and right after that another one for Sym 2.5 or so?

**Comment by nitriques** [comment]
> Huh, another question, will this XSFR support break compatibility with Symphony 2.4? 

2.4 no. 2.3, yes, it does. We could use php's [is_callable](http://php.net/manual/en/function.is-callable.php) or class_exists('XSRF') to make it work with 2.3 again.

XSRF has been introduced in 2.4 (see https://github.com/symphonycms/symphony-2/wiki/Migration-Guide-to-2.4-for-Developers)
