### ISSUE TITLE
Can't delete single activities

### ISSUE THREAD

**Issue by moretaste** [symphonists/tracker#27]
It is not possible (2.6) to select a single activity

**Comment by nitriques** [comment]
Are you getting an error ? Was it possible before ?

**Comment by moretaste** [comment]
There is no error. Lines are just not selectable on the 2.6 version

I have tracker running on a 2.3 version without problems

**Comment by nilshoerrmann** [comment]
I think the table needs a special data attribute that specifies the interactivity. Check the markup of other backend tables to find the correct attribute.

**Comment by moretaste** [comment]
Fixed by changing https://github.com/symphonists/tracker/blob/master/content/content.index.php#L111 to 
```
            Widget::TableBody($tbody), 'selectable', null,
            array('role' => 'directory', 'aria-labelledby' => 'symphony-subheading', 'data-interactive' => 'data-interactive')

```

**Comment by moretaste** [comment]
I made a pull request for this (first time so I hope I do it the right way ;-))
