### ISSUE TITLE
Consider setting the limit to 'manager'

### ISSUE THREAD

**Issue by nitriques** [symphonists/tracker#33]
Instead of developer.

**Comment by nitriques** [comment]
Any feedback ? If not, I'll do it ;)

Maybe manager won't have the "clear" option ?

**Comment by animaux** [comment]
How about making that configurable? :)

**Comment by nitriques** [comment]
> How about making that configurable? :)

That could also be an option. I've done it a couple of time, works great.

**Comment by nitriques** [comment]
Finally, not configurable, but read only. Reopen if you need configurable.

**Comment by animaux** [comment]
Good choice! Thanks.
