### ISSUE TITLE
Unidentified users

### ISSUE THREAD

**Issue by nilshoerrmann** [symphonists/tracker#35]
I just found this in the Tracker logs:

> An unidentified user (141.41.XXX.XXX) logged in to the back end.

How is it possible that someone who logged into the backend is unknown. I'd expect to read the user's name here.

**Comment by nitriques** [comment]
Which symphony version ? and extension version ?

**Comment by nilshoerrmann** [comment]
Sorry for not mentioning:
Latest extension version, Symphony 2.7dev.

**Comment by nitriques** [comment]
No probs, just wanted to make sure it's not a compat issue.

**Comment by animaux** [comment]
Using the `members` extension, the users are not identified properly when using an `member e-mail`-field as identification rather than a username.

**Comment by nilshoerrmann** [comment]
Alex, do you refer to all Member's actions or does this affect the aforementioned problem as well where _backend logins_ are not handled properly?

**Comment by animaux** [comment]
Only frontend member actions. This is probably a different issue.

**Comment by nilshoerrmann** [comment]
Alright, thanks for clarifying. Sounds like there is some kind of motif though.

**Comment by animaux** [comment]
I could fix this for an installtion by replacing the `member`-call with an `e-mail`-call for the members part. So in this case it probably needs to check which field is used for identification before trying to output an assumed field.

**Comment by nitriques** [comment]
@animaux I can help you with code review if needed! Ping me on gitter. Hi @nilshoerrmann !

**Comment by nilshoerrmann** [comment]
Hey, Nicolas :)

**Comment by animaux** [comment]
I think I fixed the member-part of the problem. Pretty straight forward, but since I’m not a programmer, please do have a look @nitriques `:)` https://github.com/symphonists/tracker/pull/37

**Comment by nitriques** [comment]
> but since I’m not a programmer, 

Everybody can be a programmer. You are definitely one. Code reviews are always a good thing ;)

**Comment by animaux** [comment]
@nitriques thanks for the encouragement, I’m trying 👍

**Comment by nitriques** [comment]
Keep trying. That's the only way to learn. Rinse and repeat as long as you find it rewarding ;)

**Comment by animaux** [comment]
Most of the times it feels like [this](https://twitter.com/bnap48/status/836331335941832705).

**Comment by nitriques** [comment]
http://www.hanselman.com/blog/ImAPhonyAreYou.aspx after 14 years of programming, the feeling is still strong.

**Comment by animaux** [comment]
Very true and good read, thanks :)

**Comment by nitriques** [comment]
My pleasure ;)
