### ISSUE TITLE
Symphony Warning: A non-numeric value encountered

### ISSUE THREAD

**Issue by animaux** [symphonists/tracker#41]
+ Symphony 2.7.0
+ PHP 7.0
+ Tracker 2.1.1

I get the following error when trying to access `/symphony/extension/tracker/`

`An error occurred in …/extensions/tracker/content/content.index.php around line 157`

		152 ;
		153 $per_page = Symphony::Configuration()->get('pagination_maximum_rows', 'symphony');
		154 $total_entries = Symphony::Database()->fetchVar('count', 0, $sql);
		155 $remaining_entries = max(0, $total_entries - ($start + $per_page));
		156 $total_pages = max(1, ceil($total_entries * (1 / $per_page)));
		157 $remaining_pages = max(0, $total-pages - $current_page);
		158
		159 if ($total_pages > 1) {
		160 $ul = new XMLElement('ul');
		161 $ul->setAttribute('class', 'page');

## Backtrace

		[/…/extensions/tracker/content/content.index.php:157]
			GenericErrorHandler::handler();
		[/…/symphony/lib/toolkit/class.administrationpage.php:490]
			contentExtensionTrackerIndex->view();
		[/…/symphony/lib/core/class.administration.php:205]
			AdministrationPage->build();
		[/…/symphony/lib/core/class.administration.php:483]
			Administration->__buildPage();
		[/…/symphony/lib/boot/func.utilities.php:253]
			Administration->display();
		[/…/symphony/lib/boot/func.utilities.php:235]
			symphony_launcher();
		[/…/index.php:19]
			symphony();

**Comment by animaux** [comment]
Probably a `PHP 7` problem: https://stackoverflow.com/questions/42044127/warning-a-non-numeric-value-encountered

**Comment by animaux** [comment]
Looks like a typo in #157.

**Comment by animaux** [comment]
Looks like this was already fixes, but not in my copy … 

https://github.com/symphonists/tracker/commit/e421305aafda211994035a14cce90b51fd884ade

**Comment by nitriques** [comment]
> Looks like this was already fixed, but not in my copy …

When working with a fork, it is a good idea to add the original repo as a remote, typically called `upstream`. That way, you can always update your local copy and your remote, by doing

```
git pull upstream branch
git push origin branch
``

`git fetch --all` is quite useful too.

**Comment by animaux** [comment]
Thanks @nitriques will add this to my cheatsheet `;)`
