### ISSUE TITLE
Tested Tracking Ability, Four Things Untracked

### ISSUE THREAD

**Issue by jesseray** [symphonists/tracker#5]
I tested the extension thoroughly on Symphony 2.2.1 to see if everything worked properly. There were no PHP errors and most activity was tracked, but four important activities available on a fresh Symphony installation were not: event deletions, data source deletions, utility deletions, and page template updates. Below is the checklist I used while testing your extension (+ success, - failure):

	Page		Create		+
				Update		+
				Delete		+
	Section		Create		+
				Update		+
				Delete		+
	Event		Create		+
				Update		+
				Delete		-
	Data Source	Create		+
				Update		+
				Delete		-
	Utility		Create		+
				Update		+
				Delete		-
	Template	Update		-
	Author		Create		+
				Update		+
				Delete		+
	Preferences	Update		+
	Extension	Enable		+
				Disable		+
				Uninstall	+

**Comment by cmnstmntmn** [comment]
any ideea why Deletion .. isn't tracked ?

**Comment by jurajkapsz** [comment]
> any ideea why the Delete event .. isn't tracked ?

Yes, I also noticed this. @nitriques ?

**Comment by nitriques** [comment]
> any ideea why the Delete event .. isn't tracked ?

It's been forgotten! Feel free to send a PR tracking it.

**Comment by nilshoerrmann** [comment]
Which delete event are you talking about? I just checked and it seems like tracker logs all actions listed above.

**Comment by jurajkapsz** [comment]
> Which delete event are you talking about? I just checked and it seems like tracker logs all actions listed above.

I've deleted an author and an entry, and no records of both actions in Tracker.

**Comment by nitriques** [comment]
>  no records of both actions in Tracker.

One problem we are facing is the fact that if the description is null, the records does not show up.

I would vote to display everything, all the time, even if a description can't be found.

Also, deleting an entry does logs the action: but since it can't log the section id, it won't have a description and therefore won't show up.

**Comment by tmslnz** [comment]
Perhaps lost in my pull request, I’ve added a NULL check in the `validateSection` function which resolves (for me at least) the issue of entry deletes not being passed to the logger. See commit https://github.com/symphonists/tracker/commit/db74b152ff8119cdb429f5d29ad33ed64138798a

In context: https://github.com/symphonists/tracker/blob/db74b152ff8119cdb429f5d29ad33ed64138798a/extension.driver.php#L655

**Comment by nitriques** [comment]
> Perhaps lost in my pull request, I’ve added a NULL check 

No it's not lost! They are just not displayed. BTW, which version of symphony are you testing againts @tmslnz ?

**Comment by tmslnz** [comment]
I'm working on 2.6.7

The missing entry delete event was due to validateSection returning false, due to the $section_id being empty, due to the $context of an entry delete event missing section information due to the fact that the entry is no more and we only have an ID left to work with. Pardon the due chain.

**Comment by nitriques** [comment]
Hahah:) I've fixed this (see 8d16bec)

**Comment by nitriques** [comment]
Hopefully this is fixed in `1.5.0`. Thanks y'all.

**Comment by tmslnz** [comment]
Have you had a chance to test this change? In my testing it wasn't fixing the behaviour. preDelete still only passes entry IDs, as the API docs say.

**Comment by nitriques** [comment]
Yeah I've tested everything that still exists in `2.6.7` :+1:

**Comment by tmslnz** [comment]
Wouldn't it be better to fix this at the root in Symphony rather than working around the issue in the extension? Do you have familiarity with symphony core?

**Comment by nitriques** [comment]
> Wouldn't it be better to fix this at the root in Symphony rather than working around the issue in the extension?

It will. I have done major work around the delegates ;)  section_id will be provided in the next releases.

But

>  preDelete still only passes entry IDs,

The entry still exists in the DB at this point, so it's easy to fetch the section_id.

> Do you have familiarity with symphony core?

Yes ;)

**Comment by tmslnz** [comment]
Nice. Looking forward to it. But good that we have a fixed extension for now!

**Comment by nitriques** [comment]
:+1:
